// Generated by CoffeeScript 2.6.1
(function() {
  var array, editorOptions, examples, format, input, object, output, parse, say, select, tokenize, translate;

  libra.global();

  select = html.select;

  ({tokenize, parse, translate} = zq);

  editorOptions = {
    fontSize: "16pt",
    highlightActiveLine: false,
    highlightGutterLine: false,
    showPrintMargin: false,
    showGutter: true,
    theme: "ace/theme/merbivore"
  };

  input = ace.edit("input");

  input.setOptions(editorOptions);

  output = ace.edit("output");

  output.setOptions(editorOptions);

  output.setReadOnly(true);

  output.renderer.$cursorLayer.element.style.display = "none";

  input.setValue(vault.get('last'));

  input.gotoLine(0);

  input.focus();

  format = function(code) {
    return prettier.format(code, {
      parser: 'babel',
      plugins: prettierPlugins
    });
  };

  array = function(...arr) {
    return [...arr];
  };

  object = function(obj) {
    return obj;
  };

  say = function(...args) {
    var newline, text;
    text = output.getValue();
    newline = text.length > 0 ? '\n' : '';
    return output.setValue(text + newline + args.join(' '));
  };

  select('#controls').onclick = function(evt) {
    var ast, error, jsCode, label, tokens, zqCode;
    try {
      if (!evt.target.classList.contains('button')) {
        return;
      }
      label = evt.target.innerText;
      zqCode = input.getValue();
      tokens = tokenize(zqCode);
      ast = parse(tokens);
      jsCode = translate(ast);
      vault.set('last', input.getValue());
      if (label === 'tokens') {
        output.setValue((format(JSON.stringify(tokens))).slice(0, -1));
      }
      if (label === 'parse tree') {
        output.setValue((format(`(${JSON.stringify(ast)})`)).slice(0, -1));
      }
      if (label === 'javascript') {
        output.setValue((format(jsCode)).slice(0, -1));
      }
      if (label === 'evaluate') {
        output.setValue('');
        eval(jsCode);
      }
      if (label === 'examples') {
        output.setValue(examples);
      }
      if (label === 'clear') {
        output.setValue('');
      }
      return output.gotoLine(1000000);
    } catch (error1) {
      error = error1;
      output.setValue('' + error);
      return output.gotoLine(1000000);
    }
  };

  addEventListener("keydown", function(evt) {});

  //log evt
  //evt.preventDefault()
  examples = `let animals = array 'rabits 'snakes 'whales 'ducks
for animal in animals
    say "i like [ animal ]"
say "they are all cute"`;

}).call(this);
